### ISSUE TITLE
OBSOLETE: ASSISIarenaUI 'hide airflow marker' not working properly

### ISSUE THREAD

**Issue by mbodi** [larics/assisi-python#53] opened 2016-04-12 15:00 UTC
When clicking on 'hide airflow marker', the temperature markers dissapear.... instead of the airflow markers

**Comment by mbodi** [comment] 2016-04-12 15:03
is obsolete, stupid me opend the issue in the wrong place. Don't know how to delete it! Sorry!

**Comment by dmiklic** [comment] 2016-04-12 16:04
Duplicate of larics/assisi-arena-ui#35

**Closed by dmiklic** 2016-04-12 16:04 UTC
